loadstring(game:HttpGet("https://icxy.xyz/NovaGui/CreateAScript", true))()
--//Jotaro
--//Dio
--//Kira
--//Diego Brando
--//Diavolo
--//Goku
--//Goku Black
--//Vegeta
--// Updating Soon!

local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("ARIES ANIME VOICELINES GUI Made By Larry#8203", "DarkTheme")
local Main = Window:NewTab("Jotaro Mode")
local MainSection = Main:NewSection("Jotaro Mode")
MainSection:NewLabel("Summon Voiclines")
MainSection:NewButton("Star Platinum : OverHeaven", "", function()
chat("Star Platinum : OverHeaven")
    PlaySound(5684695930, true)
    wait(1)
end)
MainSection:NewButton("Star Platinum, Za Warudo!", "", function()
chat("Star Platinum, Za Warudo!")
    PlaySound(5736107502, true)
    wait(1)
end)
MainSection:NewButton("Star Platinum!", "", function()
chat("Star Platinum!")
    PlaySound(2554017604, true)
    wait(1)
end)
MainSection:NewLabel("Jotaro Speaking")
MainSection:NewButton("Yare Yare Daze...", "", function()
chat("Yare Yare Daze...")
    PlaySound(6670645219, true)
    wait(1)
end)
MainSection:NewButton("Yare Yare Daze..", "", function()
chat("Yare Yare Daze..")
    PlaySound(8883559770, true)
    wait(1)
end)
MainSection:NewButton("Shut up! Don't be such a pain, woman!", "", function()
chat("Shut up! Don't be such a pain, woman!")
    PlaySound(6066726827, true)
    wait(1)
end)
MainSection:NewButton("Time is now soon to flow...!", "", function()
chat("Time is now soon to flow...!")
    PlaySound(6769327870, true)
    wait(1)
end)
MainSection:NewButton("DIO!", "", function()
chat("DIO!")
    PlaySound(8366433287, true)
    wait(1)
end)
MainSection:NewButton("I'll be the judge!", "", function()
chat("I'll be the judge!")
    PlaySound(5344619446, true)
    wait(1)
end)
MainSection:NewButton("You Will Definitely Pay!", "", function()
chat("You Will Definitely Pay!")
    PlaySound(4903895449, true)
    wait(1)
end)
MainSection:NewButton("ORA ORA ORA ORA ORA!", "", function()
chat("ORA ORA ORA ORA ORA ORA ORA ORAA")
    PlaySound(6678126154, true)
    wait(1)
end)
MainSection:NewButton("But For You, I Feel No Pity At All..", "", function()
chat("But For You, I Feel No Pity At All..")
    PlaySound(6678126154, true)
    wait(1)
end)
MainSection:NewButton("I Held Back..", "", function()
chat("I Held Back..")
    PlaySound(5261021079, true)
    wait(1)
end)
MainSection:NewButton("Shut up!", "", function()
chat("Shut up!")
    PlaySound(8769065286, true)
    wait(1)
end)
MainSection:NewButton("Huh!?!?", "", function()
chat("Huh!?!?")
    PlaySound(8366720886, true)
    wait(1)
end)
local u = Window:NewTab("Dio Mode")
local Dio = u:NewSection("Dio Mode")
Dio:NewButton("ZA WARUDO : OVER HEAVEN", "", function()
chat("ZA WARUDO : OVER HEAVEN")
    PlaySound(5129686200, true)
    wait(1)
end)
Dio:NewButton("MUDA MUDA MUDA MUDA MUDA MUDAA", "", function()
chat("MUDA MUDA MUDA MUDA MUDA MUDA MUDAA")
    PlaySound(4968518358, true)
    wait(1)
end)
Dio:NewButton("you dare to resist my reality?!", "", function()
chat("You Dare To Resist My Reality?!")
    PlaySound(3516206013, true)
    wait(1)
end)
Dio:NewButton("This Is Reality!", "", function()
chat("This Is Reality!")
    PlaySound(3516209683, true)
    wait(1)
end)
Dio:NewButton("reality bend to my will", "", function()
chat("Reality Bend To My Will.")
    PlaySound(3520725457, true)
    wait(1)
end)
Dio:NewButton("no one can destroy my reality", "", function()
chat("No One Can Destroy My Reality.")
    PlaySound(3520733618, true)
    wait(1)
end)
Dio:NewButton("this is the path to heaven", "", function()
chat("This Is The Path To Heaven.")
    PlaySound(3520741614, true)
    wait(1)
end)
Dio:NewButton("You Fool!", "", function()
chat("You Fool!")
    PlaySound(2554775814, true)
    wait(1)
end)
Dio:NewButton("This is the end!", "", function()
chat("This Is The End!")
    PlaySound(2558554898, true)
    wait(1)
end)
Dio:NewButton("Weak!", "", function()
chat("Weak!")
    PlaySound(4148531112, true)
    wait(1)
end)
local p = Window:NewTab("Kira Mode")
local Kira = p:NewSection("Kira Mode")
Kira:NewLabel("Adding More If I Can")
Kira:NewButton("Killer Queen!", "", function()
chat("Killer Queen!")
    PlaySound(2652080817, true)
    wait(1)
end)
Kira:NewButton("Third Bomb!", "", function()
chat("Third Bomb!")
    PlaySound(2652099910, true)
    wait(1)
end)
local p = Window:NewTab("Diego Brando Mode")
local Diego = p:NewSection("Diego Brando Mode")
Diego:NewLabel("Adding More If I Can")
Diego:NewButton("Time Resumes!", "", function()
chat("Time Resumes")
    PlaySound(3084539117, true)
    wait(1)
end)
Diego:NewButton("WRYYYYYYYYYYYAAAAAAAH!", "", function()
chat("WRYYYYYYYYYYYAAAAAAAH!")
    PlaySound(3084528387, true)
    wait(1)
end)
Diego:NewButton("USHAAAAAAAAAAA!", "", function()
chat("USHAAAAAAAAAAA!")
    PlaySound(3084502155, true)
    wait(1)
end)
Diego:NewButton("Za Warudo! Time Resumes!", "", function()
chat("Za Warudo! Time Resumes!")
    PlaySound(3084495179, true)
    wait(1)
end)
local r = Window:NewTab("Diavolo Mode")
local Diavolo = r:NewSection("Diavolo Mode")
Diavolo:NewButton("This is king Crimson's ability", "", function()
chat("This is king Crimson's ability")
    PlaySound(3373967354, true)
    wait(1)
end)
Diavolo:NewButton("King Crimson!", "", function()
chat("King Crimson!")
    PlaySound(3373956700, true)
    wait(1)
end)
Diavolo:NewButton("Take This!", "", function()
chat("Take This!")
    PlaySound(3373975760, true)
    wait(1)
end)
Diavolo:NewButton("This Is A Test...", "", function()
chat("This Is A Test...")
    PlaySound(3374531743, true)
    wait(1)
end)
Diavolo:NewButton("You Vile Pukes!", "", function()
chat("You Vile Pukes!")
    PlaySound(6120821768, true)
    wait(1)
end)
Diavolo:NewButton("I, Diavolo. Will be king!", "", function()
chat("I, Diavolo. Will be king!")
    PlaySound(5278196952, true)
    wait(1)
end)
Diavolo:NewButton("A person grows once...", "", function()
chat("A person grows once...")
    PlaySound(6665063219, true)
    wait(1)
end)
Diavolo:NewButton("What you Just saw, What just hit you, was ME!", "", function()
chat("What you Just saw, What just hit you, was ME!")
    PlaySound(5258899114, true)
    wait(1)
end)
local p = Window:NewTab("Extra Voicelines")
local Goku = p:NewSection("Goku Mode")
Goku:NewButton("Hey! Its Me Goku", "", function()
chat("Hey! Its Me Goku")
PlaySound(5612259294, true)
end)
Goku:NewButton("Ultra Instic Theme Song", "", function()
chat("...")
PlaySound(6427919074, true)
end)
Goku:NewButton("Kaioken! 10X!", "", function()
chat("Kaioken! 10X!")
PlaySound(1574062497, true)
end)
Goku:NewButton("Get Ready, For The Real Deal!", "", function()
chat("Get Ready, For The Real Deal!")
PlaySound(3993574860, true)
end)
Goku:NewButton("RAHHHH.. RAHHHHHHHHHHHHHHHH!!", "", function()
chat("RAHHHH.. RAHHHHHHHHHHHHHHHH!!")
PlaySound(2661734130, true)
end)
Goku:NewButton("HEEEEEEEEEEEEEEEEEEEEEHHHHHHH AHHH!!!", "", function()
chat("HEEEEEEEEEEEEEEEEEEEEEHHHHHHH AHHH!!!")
PlaySound(2659098182, true)
end)
Goku:NewButton("HEEEEEEEEEEEEEEEEEEEEEHHHHHHH AHHH!!!", "", function()
chat("HEEEEEEEEEEEEEEEEEEEEEHHHHHHH AHHH!!!")
PlaySound(2659098182, true)
end)
Goku:NewButton("RAHHHHHGGGGHHHHHHHHHHHHHH!!!!", "", function()
chat("RAHHHHHGGGGHHHHHHHHHHHHHH!!!!")
PlaySound(2659098182, true)
end)
local Vegeta = p:NewSection("Vegeta Mode")
Vegeta:NewButton("FINAL FLASH!", "", function()
chat("FINAL FLASH!")
PlaySound(950551676, true)
end)
local GokuBlack = p:NewSection("Goku Black Mode")
GokuBlack:NewButton("My Vision For The World Shall Be Realized!", "", function()
chat("My Vision For The World Shall Be Realized!")
PlaySound(966261603, true)
end)
GokuBlack:NewButton("You Will Kneel Before Me!", "", function()
chat("You Will Kneel Before Me!")
PlaySound(966268002, true)
end)
GokuBlack:NewButton("Feel The Fury Of A God!", "", function()
chat("Feel The Fury Of A God!")
PlaySound(966264954, true)
end)
GokuBlack:NewButton("How Dare You, Defy A God!", "", function()
chat("How Dare You, Defy A God!")
PlaySound(966270845, true)
end)
GokuBlack:NewButton("The Peaful World Has No Need For Humans, Your Pointless!", "", function()
chat("The Peaful World Has No Need For Humans, Your Pointless!")
PlaySound(966269704, true)
end)
GokuBlack:NewButton("Don't You Dare Keep Me Waiting!", "", function()
chat("Don't You Dare Keep Me Waiting!")
PlaySound(966262774, true)
end)


local Main = Window:NewTab("GUI Settings")
local Section = Main:NewSection("GUI Settings")
Section:NewKeybind("Toggle GUI", "e?", Enum.KeyCode.V, function()
	Library:ToggleUI()
end)
local u = Window:NewTab("Credits")
local Credits = u:NewSection("Credits")
Credits:NewLabel("Larry#8203👑⭐️")
Credits:NewLabel("MSG ME FOR ANY PROBLEMS ^^^^")
--Loadup Notification
 game.StarterGui:SetCore("SendNotification", {
    Title = "Aries Anime Voicelines Voicelines",
    Text = "Succesfully Loaded!",
    Icon = 'http://www.roblox.com/asset/?id=8191258934',
    Duration = 3;
    }) 
